# Generated by Django 4.1.5 on 2023-01-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myModel',
            new_name='eventRecord',
        ),
    ]
